#!/bin/zsh

LOG_BASE_DIR="$HOME/App/racing-api-project/racing-api-project/apps/betfair-live-prices/src/betfair_live_prices/logs"

# Ensure the log directory exists
mkdir -p "$LOG_BASE_DIR"

# Generate the log file name dynamically based on the current date
LOG_FILE_NAME="execution_$(date +%Y_%m_%d).log"
LOG_FULL_PATH="${LOG_BASE_DIR}/${LOG_FILE_NAME}"

source "$(dirname "$0")/setup_env" "betfair-live-prices"
export PYTHONPATH="$(pwd)"
python -m betfair_live_prices.main