#!/bin/zsh

LOG_BASE_DIR="$HOME/App/racing-api-project/racing-api-project/logs/trader"

# Ensure the log directory exists
mkdir -p "$LOG_BASE_DIR"

# Generate the log file name dynamically based on the current date
LOG_FILE_NAME="execution_$(date +%Y_%m_%d).log"
LOG_FULL_PATH="${LOG_BASE_DIR}/${LOG_FILE_NAME}"

source "$(dirname "$0")/setup_env" "trader"
export PYTHONPATH="$(pwd)"

# Redirect all output (stdout and stderr) to the dated log file
exec >> "$LOG_FULL_PATH" 2>&1

echo "Trader execution started at $(date)"

python -m trader.main

echo "Trader execution completed at $(date)" 