#!/bin/zsh
export LOG_LEVEL="INFO"

unset AWS_PROFILE

cd "${BETFAIR_PRICES_ROOT_DIR}"

LOG_FILE="${BETFAIR_PRICES_ROOT_DIR}/logs/running.log"
mkdir -p $(dirname "$LOG_FILE")

set -a
source "${BETFAIR_PRICES_ROOT_DIR}/.env"
set +a

cd "${BETFAIR_PRICES_ROOT_DIR}"

VENV_PATH=$(cat "${BETFAIR_PRICES_ROOT_DIR}/.python-venv")
source "${VENV_PATH}"

export PYTHONPATH=$(pwd)

python3 "${BETFAIR_PRICES_ROOT_DIR}/src/prices_updates.py" > "$LOG_FILE" 2>&1